package kr.co.nexters.together.protocol;

public enum ErrorCause {
    UNKNOWN("UNKNOWN"),
    INVALID_ARGUMENT("INVALID_ARGUMENT"),
    INSUFFICIENT_PERMISSION("INSUFFICIENT_PERMISSION"),
    NO_SUCH_ELEMENT("NO_SUCH_ELEMENT"),
    BAD_REQUEST("BAD_REQUEST"),
    NOT_ALLOWED("NOT_ALLOWED"),
    TEMPORARY_UNAVAILABLE("TEMPORARY_UNAVAILABLE"),

    INVALID_EMAIL_FORMAT("INVALID_EMAIL_FORMAT"),
    INVALID_PASSWORD_FORMAT("INVALID_PASSWORD_FORMAT"),

    INVALID_TOKEN("INVALID_TOKEN"),
    EXPIRED_TOKEN("EXPIRED_TOKEN"),
    REVOKED_TOKEN("REVOKED_TOKEN"),
    REISSUE_TOKEN("REISSUE_TOKEN"),

    ELEMENT_ALREADY_EXISTS("ELEMENT_ALREADY_EXISTS"),
    REMOVED_USER("REMOVED_USER"),
    PASSWORD_NOT_MATCH("PASSWORD_NOT_MATCH"),
    TRAVEL_PREFERENCE_LIMIT_EXCESS("TRAVEL_PREFERENCE_LIMIT_EXCESS");


    private final String cause;
    ErrorCause(String cause) {
        this.cause = cause;
    }

}
